logging:
  config: config/log4j2.xml
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cucme?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2b8&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 2000
    lettuce:
      pool:
        max-active: 200
        max-wait: 500
        max-idle: 100
        min-idle: 20

bricks:
  upload:
    saveDir:
    webPath:


