spring:
  application:
    name: cucme-manager
  profiles:
    include: core,jpa,druid,lettuce,http
    active: dev
server:
  servlet:
    context-path: /cucme-manager/

bricks:
  authentic:
    authentic-item:
      permission-urls: /test,/service,/login/**
      login-url: /
      resource-mappings:


wechat:
  appId: wx64ae0736cf9b3905
  secret: 9eee26c1d6087fd09f02c5bdacb3bf46
  open: 
    url: https://api.weixin.qq.com/sns/jscode2session?appid={0}&secret={1}&js_code={2}&grant_type=authorization_code
  token:
    url: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid={0}&secret={1}
  template:
    url: https://api.weixin.qq.com/cgi-bin/message/wxopen/template/send?access_token={0}

aliyun:
  accessKeyId: LTAInmSfhRrI2klT
  accessKeySecret: XDjmdLYlfedRhlUoEK5KH3vshqxe8X
  regionId: cn-shanghai


